@ParametersAreNonnullByDefault
@FieldsAreNonnullByDefault
@MethodsAreNonnullByDefault
package dev.jaronline.cuttingdelight.common.integration;

import dev.jaronline.cuttingdelight.core.FieldsAreNonnullByDefault;
import dev.jaronline.cuttingdelight.core.MethodsAreNonnullByDefault;
import dev.jaronline.cuttingdelight.core.ParametersAreNonnullByDefault;
