modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Jaronline/CuttingDelight/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="" #optional
displayURL="https://github.com/Jaronline/CuttingDelight"
logoFile="logo.png"
logoBlur=false
credits="${mod_credits}"
authors="${mod_authors}"
description='''${mod_description}'''
itemIcon="cuttingdelight:cutting_board"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="farmersdelight"
    mandatory=true
    versionRange="${farmers_delight_version_range}"
    ordering="AFTER"
    side="BOTH"