1.21.1:
  - "### In which Minecraft version are you experiencing this issue\\?\\n\\n1\\.21\\.1\\n"
1.20.1:
  - "### In which Minecraft version are you experiencing this issue\\?\\n\\n1\\.20\\.1\\n"
neoforge:
  - "### In which mod loader are you experiencing this issue\\?\\n\\nneoforge\\n"
forge:
  - "### In which mod loader are you experiencing this issue\\?\\n\\nforge\\n"
fabric:
  - "### In which mod loader are you experiencing this issue\\?\\n\\nfabric\\n"
quilt:
  - "### In which mod loader are you experiencing this issue\\?\\n\\nquilt\\n"
