labels:
  # Versions
  - name: "1.20.1"
    color: "95e516"
  - name: "1.21.1"
    color: "95e516"
  # Modloaders
  - name: "fabric"
    color: "dfd0b4"
  - name: "forge"
    color: "17293f"
  - name: "neoforge"
    color: "d66f37"
  - name: "quilt"
    color: "9722ff"
  # Other Projects
  - name: "root"
    color: "dcd735"
  - name: "core"
    color: "ea143d"
  - name: "common"
    color: "ea143d"
  - name: "processor"
    color: "ea143d"
  - name: "changelog"
    color: "ea143d"
  - name: "buildSrc"
    color: "056deb"
  # Gradle Misc
  - name: "gradlew"
    color: "d8c3ec"
  - name: "versions"
    color: "07ccfc"
