# Gradle settings
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Cutting Delight
modId=cuttingdelight
modName=Cutting Delight
modLicense=MIT License
modGroupId=dev.jaronline.cuttingdelight
modAuthors=Jaronline
modCredits=GhostPants, noiseless230, vectorwing, Farmer's Delight Discord Community
modDescription=A Farmer's Delight addon that makes cutting boards easier to use

# Publishing
curseProjectId=1327410
modrinthId=5oqQBDcS
