@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package dev.jaronline.cuttingdelight.common.network;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;