@ParametersAreNonnullByDefault
@FieldsAndMethodsAreNonnullByDefault
package dev.jaronline.cuttingdelight.neoforge;

import dev.jaronline.cuttingdelight.core.FieldsAndMethodsAreNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;