@ParametersAreNonnullByDefault
@MethodsAreNonnullByDefault
@FieldsAreNonnullByDefault
package dev.jaronline.cuttingdelight.common.util.function;

import dev.jaronline.cuttingdelight.common.FieldsAreNonnullByDefault;
import dev.jaronline.cuttingdelight.common.MethodsAreNonnullByDefault;
import dev.jaronline.cuttingdelight.common.ParametersAreNonnullByDefault;
