@ParametersAreNonnullByDefault
@FieldsAndMethodsAreNonnullByDefault
package dev.jaronline.cuttingdelight.neoforge.platform;

import dev.jaronline.cuttingdelight.core.FieldsAndMethodsAreNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
