@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package dev.jaronline.cuttingdelight;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;