name: Build

on:
  push:
    branches:
      - 1.20.1
  pull_request:
    branches:
      - 1.20.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Setup JDK 17
        uses: actions/setup-java@v6
        with:
          distribution: microsoft
          java-version: '17'
          cache: gradle
      - name: Build packages
        run: ./gradlew build
