name: Build

on:
  push:
    branches:
      - 1.21.1
  pull_request:
    branches:
      - 1.21.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Gradle
        uses: Jaronline/.github/actions/setup-java-gradle@main

      - name: Build with Gradle
        run: ./gradlew build
