name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Gradle
        uses: Jaronline/.github/actions/setup-java-gradle@main
        with:
          java-version: '17'

      - name: Build packages
        run: |
          ./gradlew :build
          ./gradlew :Core:build
          ./gradlew :Common:build
          ./gradlew :Processor:build
          ./gradlew :Forge:build
