name: "MC Test"

on:
  push:
    branches:
      - 1.21.1
  pull_request:
    branches:
      - 1.21.1

permissions:
  contents: read

env:
  java-version: "21"
  mc-version: "1.21.1"

jobs:
  client-test:
    name: "Test MC Client"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        modloader: [neoforge]
        include:
          - fabric-api: none
          - modloader: neoforge
            module: NeoForge
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup gradle
        uses: Jaronline/.github/actions/setup-java-gradle@main

      - name: Build mod
        run: |
          ./gradlew :Common:build
          ./gradlew :${{ matrix.module }}:build -PjarName=cuttingdelight
      
      - name: Stage mod
        run: |
          mkdir -p run/mods
          cp ${{ matrix.module }}/build/libs/cuttingdelight.jar run/mods
          
      - name: Run MC Runtime Test
        uses: headlesshq/mc-runtime-test@2a5a5bcc9d833cf22a817f3561915421dfd6a287 # 4.1.0
        with:
          mc: ${{ env.mc-version }}
          modloader: ${{ matrix.modloader }}
          regex: ${{ format('.*{0}.*', matrix.modloader) }}
          mc-runtime-test: ${{ (matrix.modloader == 'forge' && 'lexforge') || matrix.modloader }}
          java: ${{ env.java-version }}
          fabric-api: ${{ matrix.fabric-api }}

  server-test:
    name: "Test MC Server"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        modloader: [neoforge]
        include:
          - fabric-api: none
          - modloader: neoforge
            module: NeoForge
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup gradle
        uses: Jaronline/.github/actions/setup-java-gradle@main

      - name: Build mod
        run: |
          ./gradlew :Common:build
          ./gradlew :${{ matrix.module }}:build -PjarName=cuttingdelight

      - name: Stage mod
        run: |
          mkdir -p run/mods
          cp ${{ matrix.module }}/build/libs/cuttingdelight.jar run/mods

      - name: Run MC Server Test
        uses: headlesshq/mc-server-test@42de00da95e997b046a43eb9beb516494e542ba9 # 1.1.1
        with:
          mc: ${{ env.mc-version }}
          modloader: ${{ matrix.modloader }}
          java: ${{ env.java-version }}
          fabric-api: ${{ matrix.fabric-api }}
