name: "MC Test"

on:
  push:
    branches:
      - 1.20.1
  pull_request:
    branches:
      - 1.20.1

permissions:
  contents: read

env:
  java-version: "17"
  mc-version: "1.20.1"

jobs:
  client-test:
    name: "Test MC Client"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        modloader: [forge]
        include:
          - fabric-api: none
          - modloader: forge
            module: Forge
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup gradle
        uses: Jaronline/.github/actions/setup-java-gradle@main

      - name: Build mod
        run: |
          ./gradlew :Common:build
          ./gradlew :${{ matrix.module }}:build -PjarName=cuttingdelight
      
      - name: Stage mod
        run: |
          mkdir -p run/mods
          cp ${{ matrix.module }}/build/libs/cuttingdelight.jar run/mods

      - name: Run MC test client
        uses: touchtheduck/.github/actions/mc-runtime-test@main
        with:
          java-version: ${{ env.java-version }}
          minecraft-version: ${{ env.mc-version }}
          modloader: ${{ matrix.modloader }}
          fabric-api: ${{ matrix.fabric-api }}

  server-test:
    name: "Test MC Server"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        modloader: [forge]
        include:
          - fabric-api: none
          - modloader: forge
            module: Forge
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup gradle
        uses: Jaronline/.github/actions/setup-java-gradle@main

      - name: Build mod
        run: |
          ./gradlew :Common:build
          ./gradlew :${{ matrix.module }}:build -PjarName=cuttingdelight

      - name: Stage mod
        run: |
          mkdir -p run/mods
          cp ${{ matrix.module }}/build/libs/cuttingdelight.jar run/mods

      - name: Run MC test client
        uses: touchtheduck/.github/actions/mc-server-test@main
        with:
          java-version: ${{ env.java-version }}
          minecraft-version: ${{ env.mc-version }}
          modloader: ${{ matrix.modloader }}
          fabric-api: ${{ matrix.fabric-api }}
